local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("RaidBuffStatus", "enUS", true)
if not L then return end

-- Command options

	L["Show the buff report dashboard."] = true
	L["Hide the buff report dashboard."] = true
	L["Report to /raid or /party who is not buffed to the max."] = true
	L["Hide and show the buff report dashboard."] = true

-- Messages

	L["No buffs needed! (Boss)"] = true
	L["No buffs needed! (Trash)"] = true
	L["Not Well Fed"] = true
	L["Missing Arcane Intellect"] = true
	L["Missing Mark of the Wild"] = true
	L["Missing Divine Spirit"] = true
	L["Missing Power Word: Fortitude"] = true
	L["Missing Shadow Protection"] = true
	L["Flask or two Elixirs"] = true
	L["Missing a Flask or two Elixirs"] = true
	L["Battle Elixir"] = true
	L["Missing a Battle Elixir"] = true
	L["Guardian Elixir"] = true
	L["Missing a Guardian Elixir"] = true
	L["Missing buffs (Trash): "] = true
	L["Missing buffs (Boss): "] = true
	L["Warnings: "] = true
	L["Paladin has Crusader Aura"] = true
	L["PVP On"] = true
	L["PVP is On"] = true
	L["AFK"] = true
	L["Player is AFK"] = true
	L["Offline"] = true
	L["Player is Offline"] = true
	L["Shadow Resistance Aura AND Shadow Protection"] = true
	L["Paladin has Shadow Resistance Aura AND Shadow Protection"] = true
	L["Paladin Aura"] = true
	L["Paladin has no Aura at all"] = true
	L["Paladin Different Aura - Group"] = true
	L["There are more Paladins than different Auras in group"] = true
	L["Dead"] = true
	L["Player is Dead"] = true
	L["Different Zone"] = true
	L["Player is in a different zone"] = true
	L["Health less than 80%"] = true
	L["Player has health less than 80%"] = true
	L["Mana less than 80%"] = true
	L["Player has mana less than 80%"] = true
	L["Boss"] = true
	L["Trash"] = true
	L["R"] = true -- R is short for Ready
	L["Aspect Cheetah/Pack On"] = true
	L["Hunter Aspect"] = true
	L["Aspect of the Cheetah or Pack is on"] = true
	L["Hunter has no aspect at all"] = true
	L["Hunter is missing Trueshot Aura"] = true
	L["Protection paladin with no Righteous Fury"] = true
	L["No Soulstone detected"] = true
	L["Someone has a Soulstone"] = true
	L["Priest is missing Inner Fire"] = true
	L["Warlock is missing Fel Armor"] = true
	L["Druid is missing Omen of Clarity"] = true
	L["Mage is missing a Mage Armor"] = true
	L["Warning: "] = true
	L["Missing buff: "] = true
	L["Gruul's Lair"] = true
	L["Tempest Keep"] = true
	L["Serpentshrine Cavern"] = true
	L["Black Temple"] = true
	L["Sunwell Plateau"] = true
	L["Hyjal Summit"] = true
	L["Wrong flask for this zone"] = true
	L["Weapon buff"] = true
	L["Missing a temporary weapon buff"] = true
	L["(Ward of Shielding)"] = true
	L["^(Weighted %(%+%d+)"] = true
	L["^(Sharpened %(%+%d+)"] = true
	L["( Poison ?[IVX]*)"] = true
	L["(Mana Oil)"] = true
	L["(Wizard Oil)"] = true
	L["(Frost Oil)"] = true
	L["(Shadow Oil)"] = true
	L["(Weapon Coating)"] = true
	L["Wrong Paladin blessing"] = true
	L["Player has a wrong Paladin blessing"] = true
	L["Paladin blessing"] = true
	L["Player is missing at least one Paladin blessing"] = true
	L["Missing Amplify Magic"] = true
	L["RBS Dashboard Help"] = true
	L["Click buffs to disable and enable."] = true
	L["Shift-Click buffs to report on only that buff."] = true
	L["Ctrl-Click buffs to whisper those who need to buff."] = true
	L["Alt-Click on a self buff will renew that buff."] = true
	L["Alt-Click on a party buff will cast on someone missing that buff."] = true
	L["Press Escape -> Interface -> AddOns -> RaidBuffStatus for more options."] = true
	L["Remove this button from this dashboard in the buff options window."] = true
	L["Buffers: "] = true
	L["(Remove buff)"] = true
	L["Tank missing Thorns"] = true
	L["Tank with Salvation"] = true
	L["Out of range"] = true
	L["RBS Tank List"] = true
	L["Click to toggle the RBS dashboard"] = true
	L["Right-click to open the addons options menu"] = true
	L["Shaman is missing Water Shield"] = true
	L["Tank missing Earth Shield"] = true


-- Talents window

	L["Talent Specialisations"] = true
	L["Name"] = true
	L["Class"] = true
	L["Spec"] = true
	L["Specialisations"] = true
	L["Can buff Divine Spirit"] = true
	L["Can buff improved Divine Spirit level 1"] = true
	L["Can buff improved Divine Spirit level 2"] = true
	L["Can buff improved Mark of the Wild level 1"] = true
	L["Can buff improved Mark of the Wild level 2"] = true
	L["Can buff improved Mark of the Wild level 3"] = true
	L["Can buff improved Mark of the Wild level 4"] = true
	L["Can buff improved Mark of the Wild level 5"] = true
	L["Improved Health Stone level 1"] = true
	L["Improved Health Stone level 2"] = true
	L["Can create a Lightwell"] = true
	L["Can buff improved Power Word: Fortitude level 1"] = true
	L["Can buff improved Power Word: Fortitude level 2"] = true
	L["Can buff improved Demoralizing Shout level 1"] = true
	L["Can buff improved Demoralizing Shout level 2"] = true
	L["Can buff improved Demoralizing Shout level 3"] = true
	L["Can buff improved Demoralizing Shout level 4"] = true
	L["Can buff improved Demoralizing Shout level 5"] = true
	L["Can buff improved Battle Shout level 1"] = true
	L["Can buff improved Battle Shout level 2"] = true
	L["Can buff improved Battle Shout level 3"] = true
	L["Can buff improved Battle Shout level 4"] = true
	L["Can buff improved Battle Shout level 5"] = true
	L["Can buff Blessing of Kings"] = true
	L["Can buff Blessing of Sanctuary"] = true
	L["Can buff Earth Shield"] = true
	L["Has Aura Mastery"] = true

-- Options window
	L["Buff Options"] = true
	L["Is a warning"] = true
	L["Is a buff"] = true
	L["Show on dashboard"] = true
	L["Report on Boss"] = true
	L["Report on Trash"] = true
	L["Show/Report in combat"] = true

-- Blizzard addons window
	L['Appearance'] = true
	L['Skin and minimap options'] = true
	L["Minimap icon"] = true
	L['Toggle to display a minimap icon'] = true
	L['Background colour'] = true
	L['Border colour'] = true
	L['Dashboard columns'] = true
	L['Number of columns to display on the dashboard'] = true
	L['Reporting'] = true
	L['Reporting options'] = true
	L['Ignore groups 6 to 8 when reporting as these are for subs'] = true
	L['Ignore groups 6 to 8'] = true
	L['Report to self'] = true
	L['Report to raid/party'] = true
	L['Report to raid/party - requires raid assistant'] = true
	L['Report to officers'] = true
	L['Report to officer channel'] = true
	L['Shorten names'] = true
	L['Shorten names in the report to reduce channel spam'] = true
	L['Combat'] = true
	L['Combat options'] = true
	L['Disable in combat'] = true
	L['Hide dashboard and skip buff checking during combat'] = true
	L['Show in party'] = true
	L['Automatically show the dashboard when you join a party'] = true
	L['Show in raid'] = true
	L['Automatically show the dashboard when you join a raid'] = true
	L['Prepend RBS::'] = true
	L['Prepend RBS:: to all lines of report chat. Disable to only prepend on the first line of a report'] = true
	L['Show group number'] = true
	L['Show the group number of the person missing a party buff'] = true
