local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("RaidBuffStatus", "enES")
if not L then return end

-- Spanish localization
-- Last update : 04/09/2008
-- By ( Tanagra Kul Tiras EU Server )

-- Command options

	L["Show the buff report dashboard."] = "Mostrar el panel del informe de mejoras"
	L["Hide the buff report dashboard."] = "Ocultar el panel del informe de mejoras"
	L["Report to /raid or /party who is not buffed to the max."] = "Informar a /banda o /grupo quien no esta mejorado al m\195\161ximo"
	L["Hide and show the buff report dashboard."] = "Mostrar/ocultar el panel del informe de mejoras"

-- Messages

	L["No buffs needed! (Boss)"] = "No faltan mejoras! (Boss)"
	L["No buffs needed! (Trash)"] = "No faltan mejoras! (Trash)"
	L["Not Well Fed"] = "No est\195\161 bien alimentado"
	L["Missing Arcane Intellect"] = "Falta Intelecto Arcano"
	L["Missing Mark of the Wild"] = "Falta Marca de lo Salvaje"
	L["Missing Divine Spirit"] = "Falta Esp\195\173ritu Divino"
	L["Missing Power Word: Fortitude"] = "Falta Palabra de poder: entereza"
	L["Missing Shadow Protection"] = "Falta Protecci\195\179n contra las Sombras"
	L["Flask or two Elixirs"] = "Frasco o dos elixires"
	L["Missing a Flask or two Elixirs"] = "Falta Frasco o dos elixires"
	L["Battle Elixir"] = "Elixir de Batalla"
	L["Missing a Battle Elixir"] = "Falta Elixir de Batalla"
	L["Guardian Elixir"] = "Elixir Guardi\195\161n"
	L["Missing a Guardian Elixir"] = "Falta Elixir Guardi\195\161n"
	L["Missing buffs (Trash): "] = "Faltan mejoras (trash)"
	L["Missing buffs (Boss): "] = "Faltan mejoras (boss)"
	L["Warnings: "] = "Avisos: "
	L["Paladin has Crusader Aura"] = "Palad\195\173n tiene Aura del Cruzado"
	L["PVP On"] = "JcJ activo"
	L["PVP is On"] = "JcJ activo"
	L["AFK"] = "AUS"
	L["Player is AFK"] = "Jugador AUS"
	L["Offline"] = "Offline"
	L["Player is Offline"] = "Jugador Offline"
	L["Shadow Resistance Aura AND Shadow Protection"] = "Aura de resistencia a las Sombras I Protecci\195\179n contra las Sombras"
	L["Paladin has Shadow Resistance Aura AND Shadow Protection"] = "Palad\195\173n tiene Aura de resistencia a las Sombras I Protecci\195\179n contra las Sombras"
	L["Paladin Aura"] = "Aura del Palad\195\173n"
	L["Paladin has no Aura at all"] = "Palad\195\173n sin Aura"
	L["Paladin Different Aura - Group"] = "Aura de Palad\195\173n diferente - grupo"
	L["There are more Paladins than different Auras in group"] = "Hay m\195\161s paladines que Auras en un grupo"
	L["Dead"] = "Muerto"
	L["Player is Dead"] = "Jugador muerto"
	L["Different Zone"] = "Zona diferente"
	L["Player is in a different zone"] = "Jugador en una zona diferente"
	L["Health less than 80%"] = "Salud por debajo del 80%"
	L["Player has health less than 80%"] = "Jugador tiene la salud por debajo del 80%"
	L["Mana less than 80%"] = "Man\195\161 por debajo del 80%"
	L["Player has mana less than 80%"] = "Jugador tiene el man\195\161 por debajo del 80%"
	L["Boss"] = "Boss"
	L["Trash"] = "Trash"
	L["R"] = "L" -- L is short for Listo
	L["Aspect Cheetah/Pack On"] = "Aspecto del guepardo/manada activo"
	L["Hunter Aspect"] = "Aspecto del cazador"
	L["Aspect of the Cheetah or Pack is on"] = "Aspecto del guepardo o de la manada activo"
	L["Hunter has no aspect at all"] = "Cazador sin Aspecto"
	L["Hunter is missing Trueshot Aura"] = "Cazador sin Aura de disparo certero"
	L["Protection paladin with no Righteous Fury"] = "Palad\195\173n de Protecci\195\179n sin Furia Justa"
	L["No Soulstone detected"] = "Piedra de alma no detectada"
	L["Someone has a Soulstone"] = "Alguien tiene Piedra de alma"
	L["Priest is missing Inner Fire"] = "Sacerdote sin Fuego interno"
	L["Warlock is missing Fel Armor"] = "Brujo sin Armadura vil"
	L["Druid is missing Omen of Clarity"] = "Druida sin Augurio de claridad"
	L["Mage is missing a Mage Armor"] = "Mago sin armadura"
	L["Warning: "] = "Aviso"
	L["Missing buff: "] = "Falta mejora: "
	L["Gruul's Lair"] = "Guarida de Gruul"
	L["Tempest Keep"] = "El Castillo de la Tempestad"
	L["Serpentshrine Cavern"] = "Caverna Santuario Serpiente"
	L["Black Temple"] = "El Templo Oscuro"
	L["Sunwell Plateau"] = "Meseta de la Fuente del Sol"
	L["Hyjal Summit"] = "La Cima Hyjal"
	L["Wrong flask for this zone"] = "Frasco incorrecto en esta zona"
	L["Weapon buff"] = "Mejora en arma"
	L["Missing a temporary weapon buff"] = "Falta mejora temporal en arma"
	L["(Ward of Shielding)"] = "(Resguardo de escudo)"
	L["^(Weighted %(%+%d+)"] = "^(Contrapesado %(%+%d+)"
	L["^(Sharpened %(%+%d+)"] = "^(Afilado %(%+%d+)"
	L["(Poison ?[IVX]*)"] = "(Veneno ?[IVX]*)"
	L["(Mana Oil)"] = "(Aceite de Man\195\161)"
	L["(Wizard Oil)"] = "(Aceite de Zahor\195\173)"
	L["(Frost Oil)"] = "(Aceite de escarcha)"
	L["(Shadow Oil)"] = "(Aceite de las Sombras)"
	L["(Weapon Coating)"] = "(Revestimineto de armas)"
	L["Wrong Paladin blessing"] = "Bendici\195\179n de Palad\195\173n err\195\179nea"
	L["Player has a wrong Paladin blessing"] = "Jugador con Bendici\195\179n de Palad\195\173n err\195\179nea"
	L["Paladin blessing"] = "Bendici\195\179n de Palad\195\173n"
	L["Player is missing at least one Paladin blessing"] = "Jugador falto de al menos una Bendici\195\179n de Palad\195\173n"
	L["Missing Amplify Magic"] = "Falta Amplificar magia"
	L["RBS Dashboard Help"] = "Ayuda del panel RBS"
	L["Click buffs to disable and enable."] = "Clic para habilitar y deshabilitar mejoras"
	L["Shift-Click buffs to report on only that buff."] = "Shift-clic para informar en solo esa mejora"
	L["Ctrl-Click buffs to whisper those who need to buff."] = "Ctrl-clic para susurrar aquellos que necesitan mejora"
	L["Alt-Click on a self buff will renew that buff."] = "Alt-clic para renovar mejora en uno mismo"
	L["Alt-Click on a party buff will cast on someone missing that buff."] = "Alt-clic para aplicar una mejora en el grupo"
	L["Press Escape -> Interface -> AddOns -> RaidBuffStatus for more options."] = "Pulsar Escape -> Interfaz -> AddOns -> RaidBuffStatus para m\195\161s opciones"
	L["Remove this button from this dashboard in the buff options window."] = "Quitar este bot\195\179n del panel en la ventana de opciones"
	L["Buffers: "] = "Mejoradores: "
	L["Tank missing Thorns"] = "Tanque sin Espinas"
	L["Tank with Salvation"] = "Tanque sin Salvaci\195\179n"
	L["Out of range"] = "Fuera de alcance"
	L["RBS Tank List"] = "Lista de tanques RBS"
	L["Click to toggle the RBS dashboard"] = "Clic para mostrar/ocultar la ventana del RBS"
	L["Right-click to open the addons options menu"] = "Clic-dcho para abrir el men\195\186 de opciones"
	L["Shaman is missing Water Shield"] = "Cham\195\161n sin Escudo de agua"
	L["Tank missing Earth Shield"] = "Tanque sin Escudo de tierra"


-- Talents window

	L["Talent Specialisations"] = "Talentos"
	L["Name"] = "Nombre"
	L["Class"] = "Clase"
	L["Spec"] = "Espec"
	L["Specialisations"] = "Especializaci\195\179n"
	L["Can buff Divine Spirit"] = "Puede mejorar Esp\195\173ritu divino"
	L["Can buff improved Divine Spirit level 1"] = "Puede mejorar Esp\195\173ritu divino mejorado nivel 1"
	L["Can buff improved Divine Spirit level 2"] = "Puede mejorar Esp\195\173ritu divino mejorado nivel 2"
	L["Can buff improved Mark of the Wild level 1"] = "Puede mejorar Marca de lo Salvaje nivel 1"
	L["Can buff improved Mark of the Wild level 2"] = "Puede mejorar Marca de lo Salvaje nivel 2"
	L["Can buff improved Mark of the Wild level 3"] = "Puede mejorar Marca de lo Salvaje nivel 3"
	L["Can buff improved Mark of the Wild level 4"] = "Puede mejorar Marca de lo Salvaje nivel 4"
	L["Can buff improved Mark of the Wild level 5"] = "Puede mejorar Marca de lo Salvaje nivel 5"
	L["Improved Health Stone level 1"] = "Piedra de Salud mejorada nivel 1"
	L["Improved Health Stone level 2"] = "Piedra de Salud mejorada nivel 2"
	L["Can create a Lightwell"] = "Puede crear Pozo de luz"
	L["Can buff improved Power Word: Fortitude level 1"] = "Puede mejorar Palabra de poder: entereza nivel 1"
	L["Can buff improved Power Word: Fortitude level 2"] = "Puede mejorar Palabra de poder: entereza nivel 2"
	L["Can buff improved Demoralizing Shout level 1"] = "Puede mejorar Grito Desmoralizador nivel 1"
	L["Can buff improved Demoralizing Shout level 2"] = "Puede mejorar Grito Desmoralizador nivel 2"
	L["Can buff improved Demoralizing Shout level 3"] = "Puede mejorar Grito Desmoralizador nivel 3"
	L["Can buff improved Demoralizing Shout level 4"] = "Puede mejorar Grito Desmoralizador nivel 4"
	L["Can buff improved Demoralizing Shout level 5"] = "Puede mejorar Grito Desmoralizador nivel 5"
	L["Can buff improved Battle Shout level 1"] = "Puede mejorar Grito de Batalla nivel 1"
	L["Can buff improved Battle Shout level 2"] = "Puede mejorar Grito de Batalla nivel 2"
	L["Can buff improved Battle Shout level 3"] = "Puede mejorar Grito de Batalla nivel 3"
	L["Can buff improved Battle Shout level 4"] = "Puede mejorar Grito de Batalla nivel 4"
	L["Can buff improved Battle Shout level 5"] = "Puede mejorar Grito de Batalla nivel 5"
	L["Can buff Blessing of Kings"] = "Puede mejorar Bendici\195\179n de los Reyes"
	L["Can buff Blessing of Sanctuary"] = "Puede mejorar Bendici\195\179n de Salvaguardia"
	L["Can buff Earth Shield"] = "Puede mejorar Escudo de tierra"
--	L["Has Aura Mastery"] = 

-- Options window
	L["Buff Options"] = "Opciones Mejoras"
	L["Is a warning"] = "Avisos"
	L["Is a buff"] = "Mejoras"
	L["Show on dashboard"] = "Mostrar en panel"
	L["Report on Boss"] = "Informar (Boss)"
	L["Report on Trash"] = "Informar (Trash)"
	L["Show/Report in combat"] = "Mostrar/Informar en combate"

-- Blizzard addons window
	L['Appearance'] = "Aspecto"
	L['Skin and minimap options'] = "Aspecto y opciones del minimapa"
	L["Minimap icon"] =  "Icono del minimapa"
	L['Toggle to display a minimap icon'] = "Conmutar para mostrar icono del minimapa"
	L['Background colour'] = "Color del fondo"
	L['Border colour'] = "Color del borde"
	L['Dashboard columns'] = "Columnas del panel"
	L['Number of columns to display on the dashboard'] = "Numero de columnas a mostrar en el panel"
	L['Reporting'] = "Informe"
	L['Reporting options'] = "Opciones del informe"
	L['Ignore groups 6 to 8 when reporting as these are for subs'] = "Ignorar grupos 6 al 8 cuando se informa siendo estos para subs"
	L['Ignore groups 6 to 8'] = "Ignorar grupos 6 al 8"
	L['Report to self'] = "Informar a uno mismo"
	L['Report to raid/party'] = "Informar a banda/grupo"
	L['Report to raid/party - requires raid assistant'] = "Informar a banda/grupo - requiere ser asistente de banda"
	L['Report to officers'] = "Informar a oficiales"
	L['Report to officer channel'] = "Informar en el canal de oficiales"
	L['Shorten names'] = "Acortar nombres"
	L['Shorten names in the report to reduce channel spam'] = "Acortar nombres en el informe para reducir 'spam' en el canal"
	L['Combat'] = "Combate"
	L['Combat options'] = "Opciones del combate"
	L['Disable in combat'] = "Deshabilitar en combate"
	L['Hide dashboard and skip buff checking during combat'] = "Ocultar panel y omitir comprobaci\195\179n de mejoras durante el combate"
	L['Show in party'] = "Mostrar en grupo"
	L['Automatically show the dashboard when you join a party'] = "Mostrar el panel autom\195\161ticamente al entrar en el grupo"
	L['Show in raid'] = "Mostrar en banda"
	L['Automatically show the dashboard when you join a raid'] = "Mostrar el panel autom\195\161ticamente al entrar en la banda"
	L['Prepend RBS::'] = "Anteponer RBS::"
	L['Prepend RBS:: to all lines of report chat. Disable to only prepend on the first line of a report'] = "Anteponer RBS:: a todas las l\195\173neas del informe en el chat. Desabilitar para anteponer solo en la primera l\195\173nea del informe"
	L['Show group number'] = "Mostrar numero del grupo"
	L['Show the group number of the person missing a party buff'] = "Mostrar numero del grupo de la persona a la que le falta una mejora"
